import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createRpStateUi } from '../../src/features/rp-state-ui.js';
import { createRpCoreService } from '../../src/rp-core/service.js';
import { createRpExtractionFlow } from '../../src/rp-core/extraction-flow.js';
import { createRpPromptHost } from '../helpers/rp-prompt-host.mjs';
const { parseHTML } = await import(process.env.BAKEMONO_TEST_LINKEDOM || 'linkedom');
const { document, window } = parseHTML(await readFile(new URL('../../settings.html', import.meta.url), 'utf8'));
// Linkedom has no checked IDL property; provide checkbox behavior for interaction tests.
Object.defineProperty(window.HTMLInputElement.prototype, 'checked', { get() { return this.hasAttribute('checked'); }, set(value) { this.toggleAttribute('checked', !!value); }, configurable: true });
let state = {}, fail = false, focused;
window.HTMLElement.prototype.focus = function () { focused = this; };
const chat = [{ mes: '甲来到书店。' }];
const service = createRpCoreService({ getState: () => state, getChat: () => chat, saveState() {}, saveChat: async () => { if (fail) throw Error('保存失败'); } });
await service.enable();
const payload = { version: 1, state: { clock: { date: '2024-04-12T23:45' }, scene: { location: '书店' }, people: [{ name: '甲', states: [{ id: 'pain', description: '胃痛' }] }, { name: '乙' }],
    relationships: [{ from: '甲', to: '乙', kind: '朋友' }], plans: [{ title: '看海', participants: ['甲', '乙'], status: 'accepted' }], items: [{ name: '钥匙', holder: '甲', quantity: 1 }] },
    claims: [{ speaker: '乙', description: '否认交往' }] };
await service.ingest(JSON.stringify(payload), 0);
const promptHost = createRpPromptHost();
const library = promptHost.library;
const flow = createRpExtractionFlow({ getState: () => state, getChat: () => chat, service, getPrompt: () => library.current() });
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const ui = createRpStateUi({ documentRef: document, getState: () => state, service, flow, navigate() {}, escapeHtml: esc, promptLibrary: library });
const root = document.querySelector('#bakemono-rp-root');
const click = async (selector, allowError = false) => {
    const node = root.querySelector(selector); assert.ok(node, selector + '\n' + root.textContent);
    node.dispatchEvent(new window.Event('click', { bubbles: true }));
    await new Promise(resolve => setTimeout(resolve, 5));
    if (!allowError) assert.equal(root.querySelector('[role=alert]')?.textContent || null, null, root.textContent);
};
const fill = (selector, value) => { const node = root.querySelector(selector); assert.ok(node, selector); node.value = value; node.dispatchEvent(new window.Event('input', { bubbles: true })); };
const select = (selector, value) => { const node = root.querySelector(selector); assert.ok(node, selector); for (const option of node.options) option.selected = false; [...node.options].find(option => option.value === value).selected = true; node.dispatchEvent(new window.Event('change', { bubbles: true })); };
ui.bind(); ui.bind(); ui.render(); ui.renderReview();
assert.equal(document.querySelector('#bakemono-rp-review').hidden, true);
assert.equal(ui.getPendingCount(), 0);
assert.equal(root.querySelector('.rp-attention'), null);
const person = service.view().projection.people[0];
await click('.rp-story-person'); await click('[data-rp-action=edit-open]');
assert.equal(focused, root.querySelector('.rp-edit-form h3'));
fill('[data-rp-edit-field=name]', '<img src=x onerror=bad>改名');
ui.render(); assert.equal(root.querySelector('[data-rp-edit-field=name]').value, '<img src=x onerror=bad>改名');
assert.equal(root.querySelector('img,script'), null);
fail = true; await click('[data-rp-action=edit-save]', true);
assert.equal(service.view().projection.people[0].name, '甲');
assert.match(root.textContent, /保存失败/);
assert.ok(root.querySelector('[data-rp-edit-field=name]'));
fail = false; await click('[data-rp-action=edit-save]');
assert.equal(service.view().projection.people[0].name, '<img src=x onerror=bad>改名');
assert.equal(root.querySelector('img'), null);
await click('[data-rp-action=edit-open]');
fill('[data-rp-edit-field=name]', '过期草稿'); await service.configure({ inject: false });
await click('[data-rp-action=edit-save]', true); assert.match(root.textContent, /变化/);
await click('[data-rp-action=edit-cancel]');
for (const [kind, field, value] of [['relationships', 'kind', '伴侣'], ['plans', 'title', '明天看海'], ['items', 'quantity', '2'], ['locations', 'name', '旧书店']]) {
    const record = service.view().projection[kind][0];
    Object.assign(ui.navigation.get(state), { selected: { kind, id: record.id }, error: '' }); ui.render();
    await click('[data-rp-action=edit-open]'); fill('[data-rp-edit-field=' + field + ']', value);
    await click('[data-rp-action=edit-save]');
    assert.equal(service.view().projection[kind][0][field], field === 'quantity' ? Number(value) : value);
}
Object.assign(ui.navigation.get(state), { selected: null, tab: 'clock' }); ui.render();
await click('[data-rp-action=edit-clock]'); fill('[data-rp-edit-field=date]', '2024-04-13'); await click('[data-rp-action=edit-save]');
assert.equal(service.view().projection.clock.date, '2024-04-13');
await click('[data-rp-action=edit-scene]'); select('[data-rp-edit-field=location]', ''); await click('[data-rp-action=edit-save]');
assert.equal(service.view().projection.scene.location, null);
await click('[data-rp-action=edit-clock]');
root.querySelector('[data-rp-edit-field=date]').dispatchEvent(Object.assign(new window.Event('keydown', { bubbles: true }), { key: 'Escape' }));
await new Promise(resolve => setTimeout(resolve, 5)); assert.equal(root.querySelector('.rp-edit-form'), null);
Object.assign(ui.navigation.get(state), { selected: { kind: 'claims', id: state.rpCore.claims[0].id } }); ui.render();
await click('[data-rp-action=edit-open]'); fill('[data-rp-edit-field=description]', '修正的说法'); await click('[data-rp-action=edit-save]');
assert.match(root.textContent, /修正的说法/); assert.equal(state.rpCore.claims.length, 2);
Object.assign(ui.navigation.get(state), { selected: { kind: 'people', id: person.id }, floor: 0 }); ui.render();
assert.equal(root.querySelector('[data-rp-action=edit-open]'), null);
Object.assign(ui.navigation.get(state), { selected: null, floor: null, tab: 'overview' }); ui.render();
await click('[data-rp-action=settings]');
assert.equal(root.querySelector('[data-rp-setting=autoApply]'), null);
assert.equal(root.querySelectorAll('[data-rp-mode]').length, 3);
fill('[data-rp-prompt-text]', '我的简短提示词'); fill('[data-rp-prompt-name]', '恋爱预设');
ui.render(); assert.equal(root.querySelector('[data-rp-prompt-text]').value, '我的简短提示词');
await click('[data-rp-action=prompt-save-as]');
assert.equal(library.current(), '我的简短提示词'); assert.ok(flow.prompt('inline').startsWith('我的简短提示词'));
fill('[data-rp-prompt-text]', '修改后的预设'); await click('[data-rp-action=prompt-overwrite]');
assert.equal(library.list().length, 2); assert.equal(library.current(), '修改后的预设');
select('[data-rp-prompt-select]', 'default'); await click('[data-rp-action=prompt-load]');
assert.equal(library.current(), '修改后的预设'); assert.ok(root.querySelector('[data-rp-action=prompt-delete]').disabled);
fill('[data-rp-prompt-text]', '暂未验证保存'); promptHost.setSaveMode('ignore'); await click('[data-rp-action=prompt-apply]');
assert.match(root.textContent, /未核验/); assert.doesNotMatch(root.querySelector('[role=status]').textContent, /已保存/);
const selectedId = library.list().find(item => item.id !== 'default').id;
select('[data-rp-prompt-select]', selectedId); await click('[data-rp-action=prompt-load]');
promptHost.setSaveMode('persist'); await click('[data-rp-action=prompt-delete]'); assert.equal(library.list().length, 1);
const stale = root.querySelector('[data-rp-action=prompt-apply]'); state = {}; const unchanged = library.current();
stale.dispatchEvent(new window.Event('click', { bubbles: true })); await new Promise(resolve => setTimeout(resolve, 5)); assert.equal(library.current(), unchanged);
ui.render(); assert.equal(root.querySelector('.rp-edit-form, .rp-prompt-editor'), null);
const css = await readFile(new URL('../../style.css', import.meta.url), 'utf8');
assert.match(css, /\.rp-edit-field[^}]*min-width: 0/);
assert.match(css, /\.rp-prompt-editor\) \.rp-controls button[^}]*min-height: 44px[^}]*white-space: nowrap/);
console.log('PASS: automatic recording UI, all entity editors, correction audit, failed/stale saves, safe text, readonly snapshots, Escape/focus, prompt preset CRUD, committed prompt use, unconfirmed persistence and cross-chat guards. Offline DOM only.');
