export const baseStoryLedgerPreset = Object.freeze({
    id: 'bakemono-base-story-ledger',
    name: '基础表格',
    description: '角色、关系、世界、物品、约定与剧情指导。剧情摘要继续交给剪辑台，不在表格里重复保存。',
    tables: [
        {
            tableIndex: 0,
            name: '角色特征表格',
            columns: ['角色名', '性别/年龄/身高/外貌', '性格', '长期备注', '临时BUFF', '当前衣着'],
            note: '记录角色天生或不易改变的特征、长期特性、临时状态变化与当前衣着。临时BUFF包括怀孕、胃痛等阶段性变化。',
            initNode: '从已有上下文寻找已知角色并插入；角色名不能为空。',
            insertNode: '本轮出现表中没有的新角色时插入。',
            updateNode: '按剧情真实更新可变属性。先天属性不要随意修改；临时BUFF与衣着随剧情变化。',
            deleteNode: '',
            required: true,
            readOnly: false,
            allowAiEdit: true,
            inject: true,
        },
        {
            tableIndex: 1,
            name: '人物关系表格',
            columns: ['双方角色名', '基础关系(底层身份)', '当前关系(流动状态)', '相互情感态度'],
            note: '分层记录角色关系。基础关系是继母与继子、青梅竹马、仇人等稳定身份，除剧情反转外不要修改；当前关系记录秘密恋人、冷战中等流动状态；情感态度必须分清双方视角。',
            initNode: '从角色表与已有上下文中寻找角色关系并插入。',
            insertNode: '出现表中没有的新关系时插入。',
            updateNode: '角色互动、当前关系或双方情感态度发生变化时更新；基础关系仅在剧情明确反转时修改。',
            deleteNode: '',
            required: true,
            readOnly: false,
            allowAiEdit: true,
            inject: true,
        },
        {
            tableIndex: 2,
            name: '世界设定表格',
            columns: ['设定名', '类型', '详细说明', '影响范围'],
            note: '只记录基础设定中没有、且会影响剧情理解的新概念，例如建筑、地点、组织、称号、规矩、兵器或特殊物品。',
            initNode: '',
            insertNode: '正文出现基础设定中不存在、并会影响剧情的新概念时插入。',
            updateNode: '设定被补充、纠正或影响范围改变时更新。',
            deleteNode: '',
            required: false,
            readOnly: false,
            allowAiEdit: true,
            inject: true,
        },
        {
            tableIndex: 3,
            name: '重要物品表格',
            columns: ['拥有人', '物品名', '描述', '效果/意义', '来源'],
            note: '只记录具有唯一性、剧情关键性或纪念意义的物品，例如神器、钥匙、定情信物与重要礼物；不要记录普通消耗品、金钱或环境杂物。',
            initNode: '',
            insertNode: '出现影响故事发展的重要物品时，提取最重要的信息并插入。',
            updateNode: '物品的拥有人、状态、效果或剧情意义发生变化时更新。',
            deleteNode: '',
            required: false,
            readOnly: false,
            allowAiEdit: true,
            inject: true,
        },
        {
            tableIndex: 4,
            name: '约定表格',
            columns: ['日期', '双方角色名', '任务/约定内容', '完成/待完成', '结果'],
            note: '记录正文中已经成立、会影响角色后续行动的待办、计划或约定。保留未完成事项，并在出现进展或结果时更新。',
            initNode: '',
            insertNode: '本轮出现表中没有的新约定、任务或计划时插入。',
            updateNode: '约定发生改变、取得进展、完成或失效时更新。',
            deleteNode: '',
            required: false,
            readOnly: false,
            allowAiEdit: true,
            inject: true,
        },
        {
            tableIndex: 5,
            name: '剧情指导',
            columns: ['内容'],
            note: '只由用户填写的剧情指导。AI 可以读取，但不能新增、修改或删除。',
            initNode: '',
            insertNode: '禁止插入。',
            updateNode: '禁止更新。',
            deleteNode: '禁止删除。',
            required: false,
            readOnly: true,
            allowAiEdit: false,
            inject: true,
        },
    ],
});

export function createBaseStoryLedgerTables() {
    return baseStoryLedgerPreset.tables.map(table => ({
        ...table,
        columns: [...table.columns],
        columnPrompts: table.columns.map(() => ''),
        rows: [],
    }));
}
